kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-dynamic
  namespace: xxx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-sc