---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-sc
  namespace: xxx
provisioner: nfs.csi.msys.com 
parameters:
  server: nfs-server.default.svc.cluster.local
  share: /
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-dynamic
  namespace: xxx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-sc