---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-sc
provisioner: nfs.csi.msys.com
parameters:
  driver: nfs
  server: 192.168.1.104
  share: /home/nmam/nfs_root/
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-dynamic
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-sc