apiVersion: v1
kind: Pod
metadata:
  name: my-test-pod
spec:
  containers:
  - name: test-container
    image: alpine:latest
    command: ["echo"]
    volumeMounts:
      - name: my-vol
        mountPath: /
  restartPolicy: OnFailure
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: pvc-nfs-static
