apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  privileged: true
  containers:
  - name: my-ctr
    image: debian:buster-slim
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
